### ISSUE TITLE
Memory issues with MCPropagation

### ISSUE THREAD

**Issue by JamieMcMillan** [comet-toolkit/punpy#15]
I am running into an issue with excessive memory requirements which crashes my computer when it is executed. If possible, please advise whether I am using the tooling incorrectly or if this is a limitation of my resources.

Below is an MWE. Using `x_dimension_size = 100` this runs in approximately 2 s. When increasing both `x` and `y` dimensions to 1000, the system crashes during the `temperature.propagate_ds(dataset)` step.

I noted the comments in the documentation regarding memory but was unable to resolve this issue.

```python
from typing import List

import numpy as np
import xarray
from obsarray import create_ds
from punpy import MCPropagation, MeasurementFunction


class SurfaceTemperature(MeasurementFunction):
    def meas_function(self, brightness_temperature: float) -> float:
        self.prop.verbose = True
        return pow(brightness_temperature, 2)

    def get_argument_names(self) -> List[str]:
        return ["temperature"]


def main() -> xarray.Dataset:

    x_dimension_size = 100
    y_dimension_size = 100
    time_dimension_size = 2

    template = {
        "temperature": {
            "dtype": np.float32,
            "dim": ["x", "y", "time"],
            "attributes": {
                "units": "K",
                "unc_comps": ["u_temperature"],
                "flag_meanings": ["good_data", "bad_data"],
            },
        },
        "u_temperature": {
            "dtype": np.int16,
            "dim": ["x", "y", "time"],
            "attributes": {"units": "K"},
            "err_corr": [{"dim": "x", "form": "systematic", "params": [], "units": []}],
        },
        "quality_flag_time": {
            "dtype": "flag",
            "dim": ["time"],
            "attributes": {"flag_meanings": ["bad", "dubious"]},
        },
    }

    dim_size = {
        "x": x_dimension_size,
        "y": y_dimension_size,
        "time": time_dimension_size,
    }

    dataset = create_ds(template, dim_size)
    dataset["temperature"].values = 293 * np.ones(
        (x_dimension_size, y_dimension_size, time_dimension_size)
    )
    dataset["u_temperature"].values = 5 * np.ones(
        (x_dimension_size, y_dimension_size, time_dimension_size)
    )

    propagation = MCPropagation(5, dtype=np.float32, verbose=True)
    temperature = SurfaceTemperature(
        propagation,
        yvariable="surface_temperature",
        yunit="K",
        corr_dims=["x.y", "time"],
#       corr_dims=["x", "y", "time"],  # Using these two keyword arguments resolved the memory issues!
#       use_err_corr_dict=True,
    )

    return temperature.propagate_ds(dataset)


if __name__ == "__main__":
    main()
```

**Comment by pdevis** [comment]
Hi Jamie, 
When using 1000 pixels in x and 1000 pixels in y, you have 10**6 pixels in total, so a total (x.y, x.y) error correlation matrix with 10**12 elements. So indeed not surprising this leads to memory issues. 
It depends on your use case whether this is possible or not, but in these cases we often separate in (x, x) and (y,y) error correlation matrices (i.e. using corr_dims=["x", "y", "time"]).

**Comment by JamieMcMillan** [comment]
Agreed it is not surprising on this scale :D

Will explore and let you know.

**Comment by JamieMcMillan** [comment]
Your point, alongside the use of `use_err_corr_dict=True` from the [documentation](https://punpy.readthedocs.io/en/latest/content/punpy_memory_and_speed.html) was perfect! 

Combined they have enabled the use of a full size imaging sequence (1280x1024x25) in under 3 s (for this MWE).

Thanks for the support!
